### ISSUE TITLE
Etude des divergences entre les besoins de l'admin et l'API d'udata

### ISSUE THREAD

**Issue by nicolaskempf57** [datagouv/data.gouv.fr#1332]
Les travaux actuels sur la nouvelle administration ont fait apparaitre des différences entre l'API existante d'udata et les besoins produit.

## Tableau des jeux de données

- impossible de trier une liste de jeux de données par nombre de téléchargements. La donnée existe dans l'API metrics, mais n'est pas remontée par udata dans le model dataset. (https://github.com/datagouv/data.gouv.fr/issues/1339)
- impossible de trier une liste de jeux de données par nombre de fichiers.

## Demande d'adhésion à une organisation

- la liste des demandes d'adhésions ne contient pas l'email du demandeur, sachant que l'accès à cette API nécessite d'appartenir à l'organisation.

## Tableau des membres d'une organisation

- la liste des membres d'une organisation n'expose pas la date à laquelle ils ont rejoint l'organisation
- la liste des membres d'une organisation n'expose pas l'adresse e-mail de la personne. Comme le point d'accès est public, il faudra prévoir une restriction sur le champ ou un endpoint différent et sécurisé.

**Comment by maudetes** [comment]
> * impossible de trier une liste de jeux de données par nombre de téléchargements. La donnée existe dans l'API metrics, mais n'est pas remontée par udata dans le model dataset.

On peut au choix :
* Rajouter l'info dans les metrics du dataset (à computer dans [udata-metrics](https://github.com/opendatateam/udata-metrics/blob/38b7314349d733add5ff3811df5b9df3d4078001/udata_metrics/tasks.py#L77)) et donc facilement rajouter un filtre. Cela simplifierait l'affichage j'imagine plutôt que de sommer sur les ressources ?
* Utiliser un filtre `-resources.metrics.views` qui récupère le JDD avec la ressource la plus téléchargée - donc pas nécessairement le plus téléchargé en sommant les ressources
* On peut aussi décider de se baser sur les "views", mais j'imagine que c'est plus un contournement malheureux pour les utilisateurs ?

> * impossible de trier une liste de jeux de données par nombre de fichiers.

Je pense que ça nécessiterait de stocker l'info du nb de ressources (ex: dans les metrics). On pourrait ensuite filtrer dessus `-metrics.resources`.
Je me permets de dire que je ne suis pas complètement convaincue par l'usage de ce `sort` :p

> * la liste des demandes d'adhésions ne contient pas l'email du demandeur, sachant que l'accès à cette API nécessite d'appartenir à l'organisation.

Facilement ajoutable à https://github.com/opendatateam/udata/blob/b616b646c3ea3c9867bd8c44433e68f89f1d24e9/udata/core/organization/api_fields.py#L33.

> * la liste des membres d'une organisation n'expose pas l'adresse e-mail de la personne. Comme le point d'accès est public, il faudra prévoir une restriction sur le champ ou un endpoint différent et sécurisé.

Il faudrait rajouter l'info d'email [dans les user_ref_fields](https://github.com/opendatateam/udata/blob/b616b646c3ea3c9867bd8c44433e68f89f1d24e9/udata/core/user/api_fields.py#L9) et le rendre conditionnel à l'utilisateur (comme ce qui [est fait pour les admin uniquement](https://github.com/opendatateam/udata/blob/b616b646c3ea3c9867bd8c44433e68f89f1d24e9/udata/core/user/api_fields.py#L40) pour l'api_fields des users).
 
> * la liste des membres d'une organisation n'expose pas la date à laquelle ils ont rejoint l'organisation

On peut facilement rajouter `since` [dans les api_fields des membres](https://github.com/opendatateam/udata/blob/b616b646c3ea3c9867bd8c44433e68f89f1d24e9/udata/core/organization/api_fields.py#L45) sans problème.

**Comment by nicolaskempf57** [comment]
> * Rajouter l'info dans les metrics du dataset (à computer dans [udata-metrics](https://github.com/opendatateam/udata-metrics/blob/38b7314349d733add5ff3811df5b9df3d4078001/udata_metrics/tasks.py#L77)) et donc facilement rajouter un filtre. Cela simplifierait l'affichage j'imagine plutôt que de sommer sur les ressources ?

Ça me semble le plus cohérent avec le traitement des autres metrics.

> Je me permets de dire que je ne suis pas complètement convaincue par l'usage de ce sort

Je suis d'accord, j'aurais tendance à inclure cela dans le filtre de la 2e itération plutot.

**Comment by maudetes** [comment]
On va pouvoir clore ce ticket d'étude @nicolaskempf57 je pense.
L'ajout des fonctionnalités se fera dans les ticket suivants : https://github.com/datagouv/data.gouv.fr/issues/1356 et https://github.com/datagouv/data.gouv.fr/issues/1339
